# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testwebappmine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://testwebappmine.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1b52483f94314cb1b033cc23ea463249 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7510d0e95ffe4545a0b4380f03dd7476 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: testwebappmine.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1b52483f94314cb1b033cc23ea463249 }}/testimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testwebappmine'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a0c6216a466445ad89e5cb13df5b1434 }}
        images: 'testwebappmine.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1b52483f94314cb1b033cc23ea463249 }}/testimage:${{ github.sha }}'